version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static:/app/statiic
      - media:/app/media
    depends_on:
      - db

  frontend:
    build: ./frontend
      context: ../frontend
      dockerfile: Dockerfile
    env_file: .env
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static:/app/staticfiles/

  nginx:
    build: 
      context: ./infra
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/app/media
