version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/app/statiic
      - media:/app/media
    depends_on:
      - db

  frontend:
    build: ./frontend
    env_file: .env
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static:/app/staticfiles/

  nginx:
    image: ./infra
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/app/media
